using UnityEngine;

namespace MechanicsDSL.Classical
{
    /// <summary>
    /// Coupled pendulums dynamics component generated by MechanicsDSL.
    /// Two identical pendulums of mass m, length l coupled by spring k.
    ///
    /// DSL specification:
    ///   \system{coupled_pendulums}
    ///   \parameter{m}{1.0}{kg}
    ///   \parameter{l}{1.0}{m}
    ///   \parameter{k}{0.5}{N/m}
    ///   \lagrangian{
    ///       0.5*m*l^2*(\dot{theta1}^2 + \dot{theta2}^2)
    ///       + m*g*l*(cos(theta1) + cos(theta2))
    ///       - 0.5*k*l^2*(theta1-theta2)^2
    ///   }
    ///   \target{unity}
    ///
    /// Author: MechanicsDSL (github.com/MechanicsDSL)
    /// License: MIT
    /// </summary>
    [AddComponentMenu("MechanicsDSL/Classical/Coupled Pendulums")]
    [DisallowMultipleComponent]
    public class CoupledPendulumsComponent : MonoBehaviour
    {
        [Header("Physical Parameters")]
        [Range(0.01f,100f)] public float mass    = 1.0f;
        [Range(0.01f,10f)]  public float length  = 1.0f;
        [Range(0f,50f)]     public float spring  = 0.5f;
        [Range(0f,25f)]     public float gravity = 9.81f;

        [Header("Initial Conditions")]
        [Range(-Mathf.PI, Mathf.PI)] public float theta1_0 = 0.3f;
        [Range(-Mathf.PI, Mathf.PI)] public float theta2_0 = 0.0f;

        [Header("Integrator")]
        public float dt = 0.005f;
        public float driftTolerance = 1e-4f;

        [Header("Visualisation")]
        public Transform bob1Transform;
        public Transform bob2Transform;
        public bool drawGizmos = true;

        public float Theta1      { get; private set; }
        public float Theta2      { get; private set; }
        public float Omega1      { get; private set; }
        public float Omega2      { get; private set; }
        public float Energy      { get; private set; }
        public float EnergyDrift { get; private set; }
        public float SimTime     { get; private set; }
        public float NormalMode1 => (Theta1 + Theta2) / Mathf.Sqrt(2f);
        public float NormalMode2 => (Theta1 - Theta2) / Mathf.Sqrt(2f);

        private float _E0, _accumulator;

        // MechanicsDSL-generated EOM
        // d²θ₁/dt² = -(g/l)sin(θ₁) - (k/m)(θ₁-θ₂)
        // d²θ₂/dt² = -(g/l)sin(θ₂) + (k/m)(θ₁-θ₂)
        private (float dw1, float dw2) EOM(float th1, float th2) => (
            -(gravity/length)*Mathf.Sin(th1) - (spring/mass)*(th1-th2),
            -(gravity/length)*Mathf.Sin(th2) + (spring/mass)*(th1-th2)
        );

        // Hamiltonian (Noether conserved)
        private float Hamiltonian(float th1, float th2, float w1, float w2)
        {
            float T = 0.5f*mass*length*length*(w1*w1+w2*w2);
            float V = -mass*gravity*length*(Mathf.Cos(th1)+Mathf.Cos(th2))
                      + 0.5f*spring*length*length*(th1-th2)*(th1-th2);
            return T + V;
        }

        private void RK4Step(float h)
        {
            var (k1w1,k1w2) = EOM(Theta1, Theta2);
            var (k2w1,k2w2) = EOM(Theta1+.5f*h*Omega1, Theta2+.5f*h*Omega2);
            var (k3w1,k3w2) = EOM(Theta1+.5f*h*(Omega1+.5f*h*k1w1), Theta2+.5f*h*(Omega2+.5f*h*k1w2));
            var (k4w1,k4w2) = EOM(Theta1+h*(Omega1+h*k3w1), Theta2+h*(Omega2+h*k3w2));

            Theta1 += (h/6f)*(Omega1*4f + h*(k1w1+2*k2w1+2*k3w1+k4w1)/4f);
            Theta2 += (h/6f)*(Omega2*4f + h*(k1w2+2*k2w2+2*k3w2+k4w2)/4f);
            Omega1 += (h/6f)*(k1w1+2*k2w1+2*k3w1+k4w1);
            Omega2 += (h/6f)*(k1w2+2*k2w2+2*k3w2+k4w2);
            SimTime += h;
        }

        private void Awake() => Reset();

        private void FixedUpdate()
        {
            _accumulator += Time.fixedDeltaTime;
            while (_accumulator >= dt) { RK4Step(dt); _accumulator -= dt; }

            Energy      = Hamiltonian(Theta1, Theta2, Omega1, Omega2);
            EnergyDrift = Mathf.Abs((Energy - _E0) / (_E0 + 1e-10f));

            if (EnergyDrift > driftTolerance)
                Debug.LogWarning($"[MechanicsDSL] Coupled pendulums energy drift {EnergyDrift:E2}", this);

            if (bob1Transform)
                bob1Transform.localPosition = new Vector3(length*Mathf.Sin(Theta1), -length*Mathf.Cos(Theta1), 0f);
            if (bob2Transform)
                bob2Transform.localPosition = new Vector3(length*Mathf.Sin(Theta2), -length*Mathf.Cos(Theta2), 0f);
        }

        public void Reset()
        {
            Theta1 = theta1_0; Theta2 = theta2_0;
            Omega1 = 0f; Omega2 = 0f;
            SimTime = 0f; _accumulator = 0f;
            _E0 = Hamiltonian(Theta1, Theta2, Omega1, Omega2);
        }

#if UNITY_EDITOR
        private void OnDrawGizmos()
        {
            if (!drawGizmos) return;
            float th1 = Application.isPlaying ? Theta1 : theta1_0;
            float th2 = Application.isPlaying ? Theta2 : theta2_0;
            Vector3 p1 = transform.position + new Vector3(length*Mathf.Sin(th1), -length*Mathf.Cos(th1), 0);
            Vector3 p2 = transform.position + new Vector3(0,0,0) + new Vector3(2f, 0, 0)
                       + new Vector3(length*Mathf.Sin(th2), -length*Mathf.Cos(th2), 0);
            Gizmos.color = Color.yellow;
            Gizmos.DrawWireSphere(transform.position, 0.03f);
            Gizmos.DrawWireSphere(transform.position + new Vector3(2f,0,0), 0.03f);
            Gizmos.color = Color.white;
            Gizmos.DrawLine(transform.position, p1);
            Gizmos.DrawLine(transform.position + new Vector3(2f,0,0), p2);
            Gizmos.color = new Color(0.2f,0.8f,0.2f,0.9f);
            Gizmos.DrawWireSphere(p1, 0.05f);
            Gizmos.DrawWireSphere(p2, 0.05f);
        }
#endif
    }
}
