using UnityEngine;

namespace MechanicsDSL.Classical
{
    /// <summary>
    /// Double pendulum dynamics component generated by MechanicsDSL.
    ///
    /// DSL specification:
    ///   \system{double_pendulum}
    ///   \parameter{m}{1.0}{kg}
    ///   \parameter{l}{1.0}{m}
    ///   \lagrangian{
    ///       0.5*m*l^2*(2*\dot{theta1}^2 + \dot{theta2}^2
    ///                  + 2*\dot{theta1}*\dot{theta2}*cos(theta1-theta2))
    ///       + m*g*l*(2*cos(theta1) + cos(theta2))
    ///   }
    ///   \target{unity}
    ///
    /// Author: MechanicsDSL (github.com/MechanicsDSL)
    /// License: MIT
    /// </summary>
    [AddComponentMenu("MechanicsDSL/Classical/Double Pendulum")]
    [DisallowMultipleComponent]
    public class DoublePendulumComponent : MonoBehaviour
    {
        [Header("Physical Parameters")]
        [Range(0.01f, 100f)] public float mass   = 1.0f;
        [Range(0.01f, 10f)]  public float length = 1.0f;
        [Range(0f, 25f)]     public float gravity = 9.81f;

        [Header("Initial Conditions")]
        [Range(-Mathf.PI, Mathf.PI)] public float theta1_0 = 0.8f;
        [Range(-Mathf.PI, Mathf.PI)] public float theta2_0 = 0.4f;

        [Header("Integrator")]
        public float dt = 0.005f;
        public float driftTolerance = 1e-3f;

        [Header("Visualisation")]
        public Transform bob1Transform;
        public Transform bob2Transform;
        public bool drawGizmos = true;

        public float Theta1     { get; private set; }
        public float Theta2     { get; private set; }
        public float Omega1     { get; private set; }
        public float Omega2     { get; private set; }
        public float Energy     { get; private set; }
        public float EnergyDrift { get; private set; }
        public float SimTime    { get; private set; }

        private float _E0, _accumulator;

        // MechanicsDSL-generated EOM
        private void EOM(float th1, float th2, float w1, float w2,
                         out float dth1, out float dth2, out float dw1, out float dw2)
        {
            float delta = th1 - th2;
            float cosd  = Mathf.Cos(delta);
            float sind  = Mathf.Sin(delta);
            float denom = length * (2f - cosd * cosd);
            dth1 = w1; dth2 = w2;
            dw1 = ((-gravity * 2f * Mathf.Sin(th1)) - sind * (w2*w2*length + w1*w1*length*cosd)) / denom;
            dw2 = (sind * (2f*w1*w1*length + gravity*Mathf.Cos(th1) + w2*w2*length*cosd)) / denom;
        }

        // MechanicsDSL-generated Hamiltonian
        private float Hamiltonian(float th1, float th2, float w1, float w2)
        {
            float T = 0.5f * mass * length * length * (2*w1*w1 + w2*w2 + 2*w1*w2*Mathf.Cos(th1-th2));
            float V = -mass * gravity * length * (2*Mathf.Cos(th1) + Mathf.Cos(th2));
            return T + V;
        }

        private void RK4Step(float h)
        {
            float k1_th1, k1_th2, k1_w1, k1_w2;
            float k2_th1, k2_th2, k2_w1, k2_w2;
            float k3_th1, k3_th2, k3_w1, k3_w2;
            float k4_th1, k4_th2, k4_w1, k4_w2;

            EOM(Theta1,                   Theta2,                   Omega1,                   Omega2,                   out k1_th1, out k1_th2, out k1_w1, out k1_w2);
            EOM(Theta1+0.5f*h*k1_th1,    Theta2+0.5f*h*k1_th2,    Omega1+0.5f*h*k1_w1,    Omega2+0.5f*h*k1_w2,    out k2_th1, out k2_th2, out k2_w1, out k2_w2);
            EOM(Theta1+0.5f*h*k2_th1,    Theta2+0.5f*h*k2_th2,    Omega1+0.5f*h*k2_w1,    Omega2+0.5f*h*k2_w2,    out k3_th1, out k3_th2, out k3_w1, out k3_w2);
            EOM(Theta1+h*k3_th1,          Theta2+h*k3_th2,          Omega1+h*k3_w1,          Omega2+h*k3_w2,          out k4_th1, out k4_th2, out k4_w1, out k4_w2);

            Theta1 += (h/6f)*(k1_th1+2*k2_th1+2*k3_th1+k4_th1);
            Theta2 += (h/6f)*(k1_th2+2*k2_th2+2*k3_th2+k4_th2);
            Omega1 += (h/6f)*(k1_w1 +2*k2_w1 +2*k3_w1 +k4_w1);
            Omega2 += (h/6f)*(k1_w2 +2*k2_w2 +2*k3_w2 +k4_w2);
            SimTime += h;
        }

        private void Awake() => Reset();

        private void FixedUpdate()
        {
            _accumulator += Time.fixedDeltaTime;
            while (_accumulator >= dt) { RK4Step(dt); _accumulator -= dt; }

            Energy      = Hamiltonian(Theta1, Theta2, Omega1, Omega2);
            EnergyDrift = Mathf.Abs((Energy - _E0) / (_E0 + 1e-10f));

            if (EnergyDrift > driftTolerance)
                Debug.LogWarning($"[MechanicsDSL] Double pendulum energy drift {EnergyDrift:E2}", this);

            Vector3 pivot = transform.position;
            Vector3 pos1  = pivot  + new Vector3(length*Mathf.Sin(Theta1), -length*Mathf.Cos(Theta1), 0);
            Vector3 pos2  = pos1   + new Vector3(length*Mathf.Sin(Theta2), -length*Mathf.Cos(Theta2), 0);

            if (bob1Transform) bob1Transform.position = pos1;
            if (bob2Transform) bob2Transform.position = pos2;
        }

        public void Reset()
        {
            Theta1 = theta1_0; Theta2 = theta2_0;
            Omega1 = 0f;       Omega2 = 0f;
            SimTime = 0f; _accumulator = 0f;
            _E0 = Hamiltonian(Theta1, Theta2, Omega1, Omega2);
        }

#if UNITY_EDITOR
        private void OnDrawGizmos()
        {
            if (!drawGizmos) return;
            float th1 = Application.isPlaying ? Theta1 : theta1_0;
            float th2 = Application.isPlaying ? Theta2 : theta2_0;
            Vector3 pivot = transform.position;
            Vector3 bob1  = pivot + new Vector3(length*Mathf.Sin(th1), -length*Mathf.Cos(th1), 0);
            Vector3 bob2  = bob1  + new Vector3(length*Mathf.Sin(th2), -length*Mathf.Cos(th2), 0);
            Gizmos.color = Color.yellow; Gizmos.DrawWireSphere(pivot, 0.03f);
            Gizmos.color = Color.white;  Gizmos.DrawLine(pivot, bob1); Gizmos.DrawLine(bob1, bob2);
            Gizmos.color = new Color(0.2f,0.6f,1f,0.9f); Gizmos.DrawWireSphere(bob1, 0.05f);
            Gizmos.color = new Color(1f,0.4f,0.1f,0.9f); Gizmos.DrawWireSphere(bob2, 0.05f);
        }
#endif
    }
}
