using System;
using UnityEngine;

namespace MechanicsDSL.Classical
{
    /// <summary>
    /// Simple pendulum dynamics component generated by MechanicsDSL.
    ///
    /// DSL specification:
    ///   \system{pendulum}
    ///   \parameter{m}{1.0}{kg}
    ///   \parameter{l}{0.25}{m}
    ///   \lagrangian{0.5*m*l^2*\dot{theta}^2 - m*g*l*(1-cos(theta))}
    ///   \target{unity}
    ///
    /// Attach to any GameObject. The component integrates the Lagrangian
    /// equations of motion each FixedUpdate, bypassing PhysX entirely.
    /// Optionally drives a child Transform to visualise the pendulum bob.
    ///
    /// Published events:
    ///   OnEnergyDrift  — fired when |dE/E0| exceeds DriftTolerance
    ///   OnStateUpdate  — fired each integration step with current state
    ///
    /// Author: MechanicsDSL (github.com/MechanicsDSL)
    /// License: MIT
    /// </summary>
    [AddComponentMenu("MechanicsDSL/Classical/Pendulum")]
    [DisallowMultipleComponent]
    public class PendulumComponent : MonoBehaviour
    {
        // ------------------------------------------------------------------
        // Inspector-exposed physical parameters
        // (MechanicsDSL \parameter blocks)
        // ------------------------------------------------------------------
        [Header("Physical Parameters")]
        [Tooltip("Pendulum bob mass [kg]")]
        [Range(0.01f, 100f)]
        public float mass = 1.0f;

        [Tooltip("Rod length [m]")]
        [Range(0.01f, 10f)]
        public float length = 0.25f;

        [Tooltip("Gravitational acceleration [m/s^2]")]
        [Range(0f, 25f)]
        public float gravity = 9.81f;

        // ------------------------------------------------------------------
        // Initial conditions
        // ------------------------------------------------------------------
        [Header("Initial Conditions")]
        [Tooltip("Initial angle from vertical [rad]")]
        [Range(-Mathf.PI, Mathf.PI)]
        public float theta0 = 0.30f;

        [Tooltip("Initial angular velocity [rad/s]")]
        public float omega0 = 0.0f;

        // ------------------------------------------------------------------
        // Integration settings
        // ------------------------------------------------------------------
        [Header("Integrator")]
        [Tooltip("Integration timestep [s]. Should match Time.fixedDeltaTime.")]
        public float dt = 0.004f;

        [Tooltip("Energy drift warning threshold |dE/E0|")]
        public float driftTolerance = 1e-4f;

        // ------------------------------------------------------------------
        // Visualisation
        // ------------------------------------------------------------------
        [Header("Visualisation")]
        [Tooltip("Optional Transform to position at the pendulum bob location")]
        public Transform bobTransform;

        [Tooltip("Draw pivot, rod, and bob in Scene view")]
        public bool drawGizmos = true;

        // ------------------------------------------------------------------
        // Events
        // ------------------------------------------------------------------
        [Serializable] public class StateEvent : UnityEngine.Events.UnityEvent<float, float, float> { }
        [Serializable] public class DriftEvent  : UnityEngine.Events.UnityEvent<float> { }

        [Header("Events")]
        [Tooltip("Fired each step: (theta_rad, omega_rad_s, energy_J)")]
        public StateEvent OnStateUpdate;

        [Tooltip("Fired when energy drift exceeds DriftTolerance: (drift)")]
        public DriftEvent OnEnergyDrift;

        // ------------------------------------------------------------------
        // Public read-only state
        // ------------------------------------------------------------------
        public float Theta      { get; private set; }
        public float Omega      { get; private set; }
        public float Energy     { get; private set; }
        public float EnergyDrift { get; private set; }
        public float SimTime    { get; private set; }

        // ------------------------------------------------------------------
        // Private state
        // ------------------------------------------------------------------
        private float _E0;
        private float _accumulator;

        // ------------------------------------------------------------------
        // MechanicsDSL-generated: equation of motion
        // d(omega)/dt = -(g/l)*sin(theta)
        // Derived from Euler-Lagrange on the Lagrangian above.
        // ------------------------------------------------------------------
        private float EOM_dOmega(float theta) =>
            -(gravity / length) * Mathf.Sin(theta);

        // ------------------------------------------------------------------
        // MechanicsDSL-generated: Hamiltonian (Noether conserved energy)
        // H = 0.5*m*l^2*omega^2 + m*g*l*(1-cos(theta))
        // Conserved by time-translation symmetry (Noether's theorem).
        // ------------------------------------------------------------------
        private float Hamiltonian(float theta, float omega)
        {
            float T = 0.5f * mass * length * length * omega * omega;
            float V = mass * gravity * length * (1.0f - Mathf.Cos(theta));
            return T + V;
        }

        // ------------------------------------------------------------------
        // Runge-Kutta 4 integrator
        // ------------------------------------------------------------------
        private void RK4Step(float h)
        {
            float k1_th = Omega;
            float k1_om = EOM_dOmega(Theta);

            float k2_th = Omega + 0.5f * h * k1_om;
            float k2_om = EOM_dOmega(Theta + 0.5f * h * k1_th);

            float k3_th = Omega + 0.5f * h * k2_om;
            float k3_om = EOM_dOmega(Theta + 0.5f * h * k2_th);

            float k4_th = Omega + h * k3_om;
            float k4_om = EOM_dOmega(Theta + h * k3_th);

            Theta   += (h / 6.0f) * (k1_th + 2*k2_th + 2*k3_th + k4_th);
            Omega   += (h / 6.0f) * (k1_om + 2*k2_om + 2*k3_om + k4_om);
            SimTime += h;
        }

        // ------------------------------------------------------------------
        // Unity lifecycle
        // ------------------------------------------------------------------
        private void Awake()
        {
            ResetToInitialConditions();
        }

        private void FixedUpdate()
        {
            // Sub-step accumulator: decouple physics dt from Unity fixed step
            _accumulator += Time.fixedDeltaTime;
            while (_accumulator >= dt)
            {
                RK4Step(dt);
                _accumulator -= dt;
            }

            // Compute and monitor conserved energy (Noether)
            Energy      = Hamiltonian(Theta, Omega);
            EnergyDrift = Mathf.Abs((Energy - _E0) / _E0);

            if (EnergyDrift > driftTolerance)
            {
                OnEnergyDrift?.Invoke(EnergyDrift);
                Debug.LogWarning(
                    $"[MechanicsDSL] Energy drift |dE/E0| = {EnergyDrift:E2} " +
                    $"exceeds tolerance {driftTolerance:E2}. " +
                    "Consider reducing dt.", this);
            }

            OnStateUpdate?.Invoke(Theta, Omega, Energy);

            // Drive bob Transform if assigned
            if (bobTransform != null)
            {
                bobTransform.localPosition = new Vector3(
                    length * Mathf.Sin(Theta),
                    -length * Mathf.Cos(Theta),
                    0f
                );
            }
        }

        // ------------------------------------------------------------------
        // Public API
        // ------------------------------------------------------------------
        /// <summary>Reset simulation to initial conditions.</summary>
        public void ResetToInitialConditions()
        {
            Theta   = theta0;
            Omega   = omega0;
            SimTime = 0f;
            _E0     = Hamiltonian(Theta, Omega);
            Energy  = _E0;
            EnergyDrift = 0f;
            _accumulator = 0f;
        }

        /// <summary>Set state directly (e.g. from sensor fusion).</summary>
        public void SetState(float theta, float omega)
        {
            Theta = theta;
            Omega = omega;
        }

        // ------------------------------------------------------------------
        // Scene-view Gizmos
        // ------------------------------------------------------------------
#if UNITY_EDITOR
        private void OnDrawGizmos()
        {
            if (!drawGizmos) return;

            Vector3 pivot = transform.position;
            Vector3 bob   = pivot + new Vector3(
                length * Mathf.Sin(Application.isPlaying ? Theta : theta0),
               -length * Mathf.Cos(Application.isPlaying ? Theta : theta0),
                0f);

            // Pivot
            Gizmos.color = Color.yellow;
            Gizmos.DrawWireSphere(pivot, 0.02f);

            // Rod
            Gizmos.color = Color.white;
            Gizmos.DrawLine(pivot, bob);

            // Bob
            Gizmos.color = new Color(0.2f, 0.6f, 1.0f, 0.9f);
            Gizmos.DrawWireSphere(bob, 0.05f);

            // Energy drift indicator (red tint when drifting)
            if (Application.isPlaying && EnergyDrift > driftTolerance)
            {
                Gizmos.color = new Color(1f, 0.2f, 0.2f, 0.5f);
                Gizmos.DrawWireSphere(bob, 0.08f);
            }
        }
#endif
    }
}
